"""Repeated real NPC workshop permissions, material changes, save and rule boundaries."""
import unreal

def scenarios(check,wait,delay,w,pc,ui,p,c,a,s,store,base):
    unreal.SystemLibrary.execute_console_command(w,'Hearthward.Storage.CreateTestAccess',pc)
    access=unreal.GameplayStatics.get_all_actors_with_tag(w,'Hearthward.Storage.TestAccess')[0].get_component_by_class(unreal.HearthwardStorageAccessComponent)
    playerbag=p.get_component_by_class(unreal.HearthwardInventoryComponent)
    def goal(intent='craft',source='bag',limits=None):
        g=unreal.HearthwardAgentGoal()
        fields={'intent':intent,'item':'axe' if intent=='repair' else 'arrows','quantity':1 if intent=='repair' else 2,'quantity_mode':'one_owned' if intent=='repair' else 'batches','source_ref':source,'limits':limits or []}
        for k,v in fields.items():g.set_editor_property(k,v)
        return g
    for repeat in range(3):
        def ck(name,v):check(f'R{repeat+1}_{name}',v)
        ck('reset',s.load_point(base));yield delay(.2)
        c.bag.try_remove('wood',12);playerbag.try_add('wood',6)
        moved=access.transfer(playerbag,True,'wood',6,unreal.GuidLibrary.new_guid(),store.get_timeline_epoch())
        ck('seed_camp',store.get_item_count('wood')==6)
        ck('own_bag_card',a.set_structured_goal(p,c,goal()));ck('own_bag_confirm',a.confirm_candidate(a.get_candidate_id()))
        yield wait(lambda:c.get_phase()==unreal.HearthwardCompanionPhase.WAITING_AT_CAMP,30)
        ck('no_unapproved_camp_debit',store.get_item_count('wood')==6 and c.bag.get_item_count('arrow')==0 and 'MATERIAL' in c.block_reason)
        ck('camp_authorized_card',a.set_structured_goal(p,c,goal(source='camp')))
        ident=a.get_candidate_id();reentrant=[]
        def during_commit():reentrant.append(s.save_point(True))
        c.bag.on_inventory_changed.add_callable(during_commit)
        ck('camp_confirm',a.confirm_candidate(ident));ck('duplicate_confirm',not a.confirm_candidate(ident))
        yield wait(lambda:c.get_phase()==unreal.HearthwardCompanionPhase.COMPLETED,40)
        c.bag.on_inventory_changed.remove_callable(during_commit)
        ck('real_camp_cost_and_output',store.get_item_count('wood')==4 and store.get_item_count('arrow')==8 and c.get_delivered()==8)
        ck('transaction_save_rejected',bool(reentrant) and not any(reentrant))
        ck('completed_save',s.save_point(True));done=s.get_points()[-1].save_id;ck('completed_load',s.load_point(done));yield delay(.5)
        ck('no_postload_duplicate',store.get_item_count('wood')==4 and store.get_item_count('arrow')==8 and c.get_delivered()==8)
        ck('reset_disappearance',s.load_point(base));yield delay(.2)
        ck('before_disappearance_card',a.set_structured_goal(p,c,goal()));ck('before_disappearance_confirm',a.confirm_candidate(a.get_candidate_id()))
        c.bag.try_remove('wood',12)
        yield wait(lambda:c.get_phase()==unreal.HearthwardCompanionPhase.WAITING_AT_CAMP,30)
        ck('arrival_rechecks_own_materials',c.get_acquired()==0 and store.get_item_count('arrow')==0 and c.bag.get_item_count('arrow')==0)
        ck('reset_ownership',s.load_point(base));yield delay(.2)
        c.bag.try_add('axe',1)
        ck('ambiguous_own_equipment_rejected',not a.set_structured_goal(p,c,goal('repair')) and c.owned_durability.get('axe')==20)
        c.bag.try_remove('axe',1)
        ck('no_material_limit',not a.set_structured_goal(p,c,goal(limits=['no:wood'])))
        ck('cost_limit',not a.set_structured_goal(p,c,goal(limits=['max:wood:1'])))
        ck('reset_repair',s.load_point(base));yield delay(.2)
        ck('repair_card',a.set_structured_goal(p,c,goal('repair')));ident=a.get_candidate_id()
        ck('repair_confirm',a.confirm_candidate(ident));ck('repair_duplicate_confirm',not a.confirm_candidate(ident))
        p.set_actor_location(unreal.Vector(5000,-200,100),False,True)
        yield wait(lambda:c.get_phase()==unreal.HearthwardCompanionPhase.COMPLETED,30)
        ck('npc_own_position_not_player',c.owned_durability.get('axe')==100 and c.bag.get_item_count('wood')==10 and c.bag.get_item_count('rope')==3)
        ck('repair_save',s.save_point(True));fixed=s.get_points()[-1].save_id;ck('repair_load',s.load_point(fixed));yield delay(.3)
        ck('repair_receipt_restored',c.owned_durability.get('axe')==100 and c.bag.get_item_count('wood')==10)
        ck('rollback_repair',s.load_point(base));yield delay(.2)
        ck('repair_same_boundary_rollback',c.owned_durability.get('axe')==20 and c.bag.get_item_count('wood')==12 and c.bag.get_item_count('rope')==4)
        ck('active_craft_card',a.set_structured_goal(p,c,goal()));ck('active_craft_confirm',a.confirm_candidate(a.get_candidate_id()))
        active=c.get_command_id()
        ck('invalid_replacement_rejected',not a.set_structured_goal(p,c,goal(limits=['no:wood'])))
        ck('invalid_replacement_preserves_active',unreal.GuidLibrary.equal_equal_guid_guid(c.get_command_id(),active))
        rule=unreal.HearthwardAgentGoal()
        for k,v in {'intent':'rule_proposal','item':'none','quantity':0,'quantity_mode':'none','source_ref':'none','limits':['no:wood']}.items():rule.set_editor_property(k,v)
        ck('rule_card',a.set_structured_goal(p,c,rule));prior=len(a.get_player_memories())
        ck('rule_not_active_before_confirm',not any(str(x.kind)=='typed_constraint' for x in a.get_player_memories()))
        ck('rule_confirm',a.confirm_candidate(a.get_candidate_id()));ck('rule_written_once',len(a.get_player_memories())==prior+1)
        yield wait(lambda:c.get_phase()==unreal.HearthwardCompanionPhase.COMPLETED,35)
        ck('accepted_rule_version_fixed',store.get_item_count('arrow')==8)
        ck('new_goal_uses_new_rule',not a.set_structured_goal(p,c,goal()))
