"""Place limb pivots inside the measured native limb surface."""
import bpy,numpy as np
from mathutils import Vector

def recenter(arm,meshes,rig,species=None):
    xyz=[];membership={k:[] for k in rig['chains']}
    for mesh in meshes:
        names={g.index:g.name for g in mesh.vertex_groups}
        for v in mesh.data.vertices:
            xyz.append(list(v.co))
            for key,ns in rig['chains'].items():membership[key].append(sum(g.weight for g in v.groups if names[g.group] in ns))
    xyz=np.array(xyz);length=rig['axis'].get('body_reference_length_m',rig['axis']['target_length_m'])
    changes=[];new={}
    for key,ns in rig['chains'].items():
        old=[np.array(arm.data.bones[n].head_local) for n in ns]
        weight=np.array(membership[key])
        centre=(old[0][1]+old[3][1])*.5
        for i in (1,2):
            p=old[i].copy()
            if species=='hare' and not key.startswith('F'):
                # The autogenerated hind knees differ by five centimetres
                # in height, yielding reversed left/right femur/shin ratios.
                # Measure both sides at their common anatomical joint level.
                p[2]=sum(arm.data.bones[rig['chains'][k][i]].head_local.z for k in ('BL','BR'))*.5
            half=min(length*.022,abs(old[i-1][2]-old[i+1][2])*.10)
            mask=(abs(xyz[:,2]-p[2])<half)&(weight>.35)&(abs(xyz[:,0]-p[0])<length*.13)&(abs(xyz[:,1]-centre)<length*.12)
            cloud=xyz[mask]
            if len(cloud)<16:raise RuntimeError('Insufficient limb surface at '+key+' '+str(i))
            # A surface median is insensitive to a few body/tail spill weights.
            x,y=np.median(cloud[:,:2],axis=0)
            q=Vector((float(x),float(y),float(p[2])))
            new[ns[i]]=q
            changes.append({'limb':key,'bone':ns[i],'before_cm':(old[i]*100).tolist(),'after_cm':[v*100 for v in q],'surface_vertices':int(mask.sum())})
        if species=='hare' and key.startswith('F'):
            # The source's tiny scapular link begins deep inside the thorax.
            # Its attachment belongs on the measured upper foreleg surface.
            p=old[0];mask=(abs(xyz[:,2]-p[2])<length*.022)&(weight>.20)&(abs(xyz[:,0]-p[0])<length*.10)&(abs(xyz[:,1]-new[ns[1]].y)<length*.06)
            if mask.sum()>=16:
                y=float(np.median(xyz[mask,1]))
            else:y=float(old[3][1]+(new[ns[1]].y-old[3][1])*.55)
            q=Vector((float(p[0]),y,float(p[2])));new[ns[0]]=q
            changes.append({'limb':key,'bone':ns[0],'before_cm':(p*100).tolist(),'after_cm':[v*100 for v in q],'surface_vertices':int(mask.sum()),'role':'scapular attachment recentered on upper foreleg'})
    bpy.context.view_layer.objects.active=arm;arm.select_set(True);bpy.ops.object.mode_set(mode='EDIT')
    for n,p in new.items():arm.data.edit_bones[n].head=p
    for ns in rig['chains'].values():
        for a,b in zip(ns[:3],ns[1:4]):
            arm.data.edit_bones[a].tail=arm.data.edit_bones[b].head
            arm.data.edit_bones[a].align_roll(Vector((0,1,0)))
    bpy.ops.object.mode_set(mode='OBJECT')
    return changes
